# Generated by Django 3.0.5 on 2024-02-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_stream', models.CharField(max_length=100)),
                ('math_score', models.IntegerField(default=0)),
                ('physics_score', models.IntegerField(default=0)),
                ('chemistry_score', models.IntegerField(default=0)),
                ('biology_score', models.IntegerField(default=0)),
                ('computer_science_score', models.IntegerField(default=0)),
                ('accountancy_score', models.IntegerField(default=0)),
                ('business_studies_score', models.IntegerField(default=0)),
                ('economics_score', models.IntegerField(default=0)),
                ('history_score', models.IntegerField(default=0)),
                ('geography_score', models.IntegerField(default=0)),
                ('political_science_score', models.IntegerField(default=0)),
                ('psychology_score', models.IntegerField(default=0)),
                ('sociology_score', models.IntegerField(default=0)),
                ('philosophy_score', models.IntegerField(default=0)),
                ('languages_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
